export const PATH = {
  login: 'login',
  signUp: 'signup',
  memberInfo: 'memberinfo',
  myPage: 'mypage',
  storeList: 'storelist',
  storeDetail: 'storedetail',
  search: 'search',
  reservationStatus: 'reservationstatus',
  reservationWaitingDetail: 'reservationwaitingdetail',
  reservation: 'reservation',
  approveddetail: 'approveddetail',
  cancelleddetail: 'cancelleddetail',
  rejecteddetail: 'rejecteddetail',
  waitingtabdetail: 'waitingtabdetail',
} as const;
