export const PATH = {
  login: 'login',
  signUp: 'signup',
  memberInfo: 'memberinfo',
  myPage: 'mypage',
  storeList: 'storelist',
  storeDetail: 'storedetail',
  search: 'search',
  reservationStatus: 'reservationstatus',
  reservationWaitingDetail: 'reservationwaitingdetail',
  seatReservation: 'seatreservation',
  spaceReservation: 'spacereservation',
  intent: 'intent',
  approved: 'approved',
  cancelled: 'cancelled',
  rejected: 'rejected',
  waitingtab: 'waitingtab',
} as const;
